env:
    browser: true
    commonjs: true
    es6: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
    #ecmaFeatures:
    #    experimentalObjectRestSpread: true
    #    jsx: true
    sourceType: module
plugins:
    - react
globals:
    process: true
rules:
    indent:
        - error
        - 4
        - SwitchCase: 1
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    
    no-console:
        - off
    no-unused-vars:
        - error
        - varsIgnorePattern: "styles"
    react/jsx-uses-react:
        - error
    react/jsx-uses-vars:
        - error
